/* Blocks will be loaded here */
//import './best-online-casino'
//import './casino-promotion-cards'
import './testimonial'
import './game-filter'
//import './casino-promotion-rows'
import './casino-match'
import './game-guide'
import './single-advertisment-casino'
import './payment-options-list'
//import './casino-list'
import './casino-toplist'
import './common-banner'
//import './high-roller-casino-list'
import './casino-promotion'
import './article-top-content'
import './casino-software-list'
import './news-toplist'

import './casino-toplist-classic'